"""Alembic integration for Shakti — programmatic migration management.

Generates and runs Alembic migrations without requiring users to touch
alembic.ini or env.py directly.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

logger = logging.getLogger("shakti.migrations")

# Template for migrations/env.py placed inside new projects
_ENV_PY = '''"""Alembic env.py — auto-generated by Shakti. Safe to customise."""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Ensure the project root is importable
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine

# Import all models so Alembic can see the metadata, then grab Base
from app.models import *             # noqa: F401,E402
from shakti.orm import Base         # noqa: E402
from shakti.config import Config    # noqa: E402

_config = Config()
DATABASE_URL = _config.require("database.url")

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = create_async_engine(DATABASE_URL)
    async with engine.begin() as conn:
        await conn.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''

_ALEMBIC_INI = '''[alembic]
script_location = migrations
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %%H:%%M:%%S
'''


_SCRIPT_MAKO = '''\
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''


def _get_alembic_config(project_dir: Path):
    """Build an Alembic Config object pointing at the project's migrations dir."""
    try:
        from alembic.config import Config as AlembicConfig
    except ImportError as exc:
        raise RuntimeError(
            "alembic is required for migrations: pip install 'shakti-framework[orm]'"
        ) from exc

    ini = project_dir / "alembic.ini"
    if not ini.is_file():
        ini.write_text(_ALEMBIC_INI, encoding="utf-8")

    cfg = AlembicConfig(str(ini))
    cfg.set_main_option("script_location", str(project_dir / "migrations"))
    return cfg


def init_migrations(project_dir: Path) -> bool:
    """Initialise migrations/ folder (idempotent). Returns True if newly created."""
    migrations_dir = project_dir / "migrations"
    versions_dir = migrations_dir / "versions"
    env_py = migrations_dir / "env.py"

    if env_py.is_file() and (migrations_dir / "script.py.mako").is_file():
        return False

    versions_dir.mkdir(parents=True, exist_ok=True)
    env_py.write_text(_ENV_PY, encoding="utf-8")
    (migrations_dir / "script.py.mako").write_text(_SCRIPT_MAKO, encoding="utf-8")
    (migrations_dir / "README").write_text(
        "Shakti migration scripts — managed via `shakti makemigrations` / `shakti migrate`.\n"
    )
    (project_dir / "alembic.ini").write_text(_ALEMBIC_INI, encoding="utf-8")
    print("✔ Initialised migrations/")
    return True


def make_migrations(project_dir: Path, message: str = "auto") -> int:
    """Generate a new migration (alembic revision --autogenerate)."""
    from alembic import command

    init_migrations(project_dir)
    sys.path.insert(0, str(project_dir))
    cfg = _get_alembic_config(project_dir)
    try:
        command.revision(cfg, message=message, autogenerate=True)
        return 0
    except Exception as exc:
        logger.error("makemigrations failed: %s", exc)
        print(f"error: {exc}", file=sys.stderr)
        return 1


def migrate(project_dir: Path, revision: str = "head") -> int:
    """Apply migrations (alembic upgrade <revision>)."""
    from alembic import command

    init_migrations(project_dir)
    sys.path.insert(0, str(project_dir))
    cfg = _get_alembic_config(project_dir)
    try:
        command.upgrade(cfg, revision)
        return 0
    except Exception as exc:
        logger.error("migrate failed: %s", exc)
        print(f"error: {exc}", file=sys.stderr)
        return 1


def migration_history(project_dir: Path) -> int:
    """Show migration history (alembic history)."""
    from alembic import command

    init_migrations(project_dir)
    sys.path.insert(0, str(project_dir))
    cfg = _get_alembic_config(project_dir)
    command.history(cfg)
    return 0


def migration_current(project_dir: Path) -> int:
    """Show current migration head."""
    from alembic import command

    init_migrations(project_dir)
    sys.path.insert(0, str(project_dir))
    cfg = _get_alembic_config(project_dir)
    command.current(cfg, verbose=True)
    return 0
